-- MySQL Script generated by MySQL Workbench
-- Thu 16 Jan 2020 05:56:25 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Planina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Planina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Planina` (
  `idPlanina` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPlanina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dom` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Dom` (
  `idDom` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `max_kapacitet` INT NOT NULL,
  `Planina_idPlanina` INT NOT NULL,
  PRIMARY KEY (`idDom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uloga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Uloga` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Uloga` (
  `idUloga` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUloga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clanarina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clanarina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clanarina` (
  `idClanarina` INT NOT NULL AUTO_INCREMENT,
  `od` DATETIME NOT NULL,
  `do` DATETIME NOT NULL,
  PRIMARY KEY (`idClanarina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Korisnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Korisnik` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Korisnik` (
  `idKorisnik` INT NOT NULL AUTO_INCREMENT,
  `korisnicko_ime` VARCHAR(45) NOT NULL,
  `lozinka` VARCHAR(100) NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `Uloga_idUloga` INT NOT NULL,
  `Clanarina_idClanarina` INT NOT NULL,
  PRIMARY KEY (`idKorisnik`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rezervacija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rezervacija` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rezervacija` (
  `idRezervacija` INT NOT NULL AUTO_INCREMENT,
  `Korisnik_idKorisnik` INT NOT NULL,
  `Dom_idDom` INT NOT NULL,
  `od` DATETIME NOT NULL,
  `do` DATETIME NOT NULL,
  PRIMARY KEY (`idRezervacija`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Izvestaj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Izvestaj` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Izvestaj` (
  `idIzvestaj` INT NOT NULL AUTO_INCREMENT,
  `tekst` VARCHAR(123) NOT NULL,
  `Rezervacija_idRezervacija` INT NOT NULL,
  PRIMARY KEY (`idIzvestaj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Planinarska_staza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Planinarska_staza` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Planinarska_staza` (
  `idStaza` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NULL,
  `tezina` INT NOT NULL,
  `mapa` LONGBLOB NULL,
  `opis` VARCHAR(123) NULL,
  `Planina_idPlanina` INT NOT NULL,
  PRIMARY KEY (`idStaza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Znamenitost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Znamenitost` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Znamenitost` (
  `idZnamenitost` INT NOT NULL AUTO_INCREMENT,
  `opis` VARCHAR(123) NULL,
  `tip` VARCHAR(45) NOT NULL,
  `Planinarska_staza_idStaza` INT NOT NULL,
  PRIMARY KEY (`idZnamenitost`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Termin_znamenitost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Termin_znamenitost` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Termin_znamenitost` (
  `idTermin` INT NOT NULL AUTO_INCREMENT,
  `pocetak` DATETIME NOT NULL,
  `kraj` DATETIME NOT NULL,
  `Znamenitost_idZnamenitost` INT NOT NULL,
  PRIMARY KEY (`idTermin`))
 ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Poseta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Poseta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Poseta` (
  `idPoseta` INT NOT NULL AUTO_INCREMENT,
  `Termin_idTermin` INT NOT NULL,
  `Rezervacija_idRezervacija` INT NOT NULL,
  PRIMARY KEY (`idPoseta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Slika`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Slika` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Slika` (
  `idSlika` INT NOT NULL AUTO_INCREMENT,
  `slika` LONGBLOB NULL,
  `Znamenitost_idZnamenitost` INT NOT NULL,
  `Izvestaj_idIzvestaj` INT NOT NULL,
  PRIMARY KEY (`idSlika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Termin_dom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Termin_dom` ;


-- -----------------------------------------------------
-- Table `mydb`.`Komentar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Komentar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Komentar` (
  `idKomentar` INT NOT NULL AUTO_INCREMENT,
  `tekst` VARCHAR(123) NOT NULL,
  `Poseta_idPoseta` INT NOT NULL,
  PRIMARY KEY (`idKomentar`))
 ENGINE = InnoDB;